/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socket_gui;

import java.net.*;
import javax.swing.JOptionPane;

/**
 *
 * @author A.S.
 */
public class GUI_Client extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Client
     */
    private String IP_address;
    private int port_to_send, port_to_receive;
    private Socket s_send, s_receive;
    private Thread_send thr_send;
    private Thread_receive thr_receive;
    
    
    public GUI_Client() {
        initComponents();
        setVisible(true);
    }
    
    public GUI_Client(String IP_address, int port_to_send, int port_to_receive) throws Exception{
        initComponents();
        
        this.IP_address = IP_address;
        this.port_to_receive = port_to_receive;
        this.port_to_send = port_to_send;
        connect();
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Field_to_send = new javax.swing.JTextArea();
        Button_send = new javax.swing.JButton();
        Button_exit = new javax.swing.JButton();
        Label_Data_received = new javax.swing.JLabel();
        Label_data_toSend = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Field_to_receive = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");

        Field_to_send.setColumns(20);
        Field_to_send.setRows(5);
        jScrollPane2.setViewportView(Field_to_send);

        Button_send.setText("Send");
        Button_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_sendActionPerformed(evt);
            }
        });

        Button_exit.setText("Exit");
        Button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_exitActionPerformed(evt);
            }
        });

        Label_Data_received.setText("Data received:");

        Label_data_toSend.setText("Data to send:");

        Field_to_receive.setColumns(20);
        Field_to_receive.setRows(5);
        Field_to_receive.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Field_to_receive.setEnabled(false);
        jScrollPane1.setViewportView(Field_to_receive);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_data_toSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Data_received)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(Button_send, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_exit)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Data_received)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label_data_toSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Button_send)
                        .addGap(54, 54, 54)))
                .addGap(19, 19, 19)
                .addComponent(Button_exit)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_exitActionPerformed
        thr_send.stopThread();
        thr_receive.stopThread();
        System.exit(0);
    }//GEN-LAST:event_Button_exitActionPerformed

    private void Button_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_sendActionPerformed
        thr_send.send();
    }//GEN-LAST:event_Button_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_exit;
    private javax.swing.JButton Button_send;
    private javax.swing.JTextArea Field_to_receive;
    private javax.swing.JTextArea Field_to_send;
    private javax.swing.JLabel Label_Data_received;
    private javax.swing.JLabel Label_data_toSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void connect() throws Exception{
        try{
                s_send = new Socket(IP_address, port_to_send);
        } catch (Exception e){throw new Exception(e);}
        
        try{
                s_receive = new Socket(IP_address, port_to_receive);
        } catch (Exception e) {s_send.close(); throw new Exception(e);}
        
                thr_send = new Thread_send(Field_to_send, s_receive);       // Connect to receiving port on Server
                thr_receive = new Thread_receive(Field_to_receive, s_send); // Connect to sending port on server
                thr_send.start();
                thr_receive.start();
    }
    
}